// Code generated by mockery. DO NOT EDIT.
// (Checked in so the repo builds offline; regenerate via `go generate ./...`.)
package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"

	"weathercache/internal/weather"
)

type Provider struct {
	mock.Mock
}

func (m *Provider) Current(ctx context.Context, city string) (weather.Report, error) {
	args := m.Called(ctx, city)
	return args.Get(0).(weather.Report), args.Error(1)
}

// NewProvider registers the mock with the test so unmet expectations
// (e.g. an .Once() that never fired) fail the test automatically.
func NewProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *Provider {
	m := &Provider{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}
